apiVersion: v1
kind: Service
metadata:
    name: samudralajeevanalakshmiuserservice
spec:
    type: LoadBalancer
    ports:
    - port: 8082 
    selector:
        app: samudralajeevanalakshmiuserservice